[2022-02-18 02:30:40,376] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dev_to_staging.copy_to_staging manual__2022-02-18T02:30:38.809974+00:00 [queued]>
[2022-02-18 02:30:40,394] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dev_to_staging.copy_to_staging manual__2022-02-18T02:30:38.809974+00:00 [queued]>
[2022-02-18 02:30:40,395] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-18 02:30:40,396] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-18 02:30:40,397] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-18 02:30:40,417] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): copy_to_staging> on 2022-02-18 02:30:38.809974+00:00
[2022-02-18 02:30:40,427] {standard_task_runner.py:52} INFO - Started process 1385 to run task
[2022-02-18 02:30:40,440] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dev_to_staging', 'copy_to_staging', 'manual__2022-02-18T02:30:38.809974+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/dev_to_staging.py', '--cfg-path', '/tmp/tmp0w0s_zrl', '--error-file', '/tmp/tmp5g7ozm1k']
[2022-02-18 02:30:40,441] {standard_task_runner.py:77} INFO - Job 43: Subtask copy_to_staging
[2022-02-18 02:30:40,527] {logging_mixin.py:109} INFO - Running <TaskInstance: dev_to_staging.copy_to_staging manual__2022-02-18T02:30:38.809974+00:00 [running]> on host bd44ee7f0b09
[2022-02-18 02:30:40,611] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dev_to_staging
AIRFLOW_CTX_TASK_ID=copy_to_staging
AIRFLOW_CTX_EXECUTION_DATE=2022-02-18T02:30:38.809974+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-18T02:30:38.809974+00:00
[2022-02-18 02:30:40,628] {base.py:79} INFO - Using connection to: id: dev. Host: 172.17.0.2, Port: 5432, Schema: public, Login: postgres, Password: ***, extra: {}
[2022-02-18 02:30:40,749] {base.py:79} INFO - Using connection to: id: staging. Host: 172.17.0.3, Port: 5432, Schema: public, Login: postgres, Password: ***, extra: {}
[2022-02-18 02:30:40,817] {postgres.py:129} INFO - Running copy expert: COPY users TO STDOUT, filename: dump
[2022-02-18 02:30:40,829] {base.py:79} INFO - Using connection to: id: dev. Host: 172.17.0.2, Port: 5432, Schema: public, Login: postgres, Password: ***, extra: {}
[2022-02-18 02:32:49,516] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dev_to_staging.py", line 17, in copy_to_staging
    pg_dev_hook.bulk_dump(table, tempFile)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in bulk_dump
    self.copy_expert(f"COPY {table} TO STDOUT", tmp_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 135, in copy_expert
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "172.17.0.2", port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?

[2022-02-18 02:32:49,564] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=dev_to_staging, task_id=copy_to_staging, execution_date=20220218T023038, start_date=20220218T023040, end_date=20220218T023249
[2022-02-18 02:32:49,596] {standard_task_runner.py:92} ERROR - Failed to execute job 43 for task copy_to_staging
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dev_to_staging.py", line 17, in copy_to_staging
    pg_dev_hook.bulk_dump(table, tempFile)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in bulk_dump
    self.copy_expert(f"COPY {table} TO STDOUT", tmp_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 135, in copy_expert
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "172.17.0.2", port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?

[2022-02-18 02:32:49,640] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-18 02:32:49,680] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
